[package]
name = "crab-gnupg"
version = "0.1.0"
edition = "2021"

[dependencies]
codepage = "0.1.2"
encoding_rs = "0.8.35"
regex = "1.11.1"

[target.'cfg(windows)'.dependencies]
winapi = { version = "0.3.9", features = ["wincon"] }


