[package]
name = "crab-gnupg"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.38"
hostname = "0.4.0"
regex = "1.11.1"

[dev-dependencies]
rand = "0.8.5"
tempfile = "3.14.0"

[features]
test_legacy = []